// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDls57rcdK329WOALkrGEceuIY0oz2B4jc',
    appId: '1:868184915846:web:58a7224422326ae3873607',
    messagingSenderId: '868184915846',
    projectId: 'mad-ass-12a36',
    authDomain: 'mad-ass-12a36.firebaseapp.com',
    databaseURL: 'https://mad-ass-12a36-default-rtdb.firebaseio.com',
    storageBucket: 'mad-ass-12a36.appspot.com',
    measurementId: 'G-ZLL2WTQKT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVInuiMmObvJLwZb188-p6a-vG31sNg9w',
    appId: '1:868184915846:android:fb8edb4c206060f0873607',
    messagingSenderId: '868184915846',
    projectId: 'mad-ass-12a36',
    databaseURL: 'https://mad-ass-12a36-default-rtdb.firebaseio.com',
    storageBucket: 'mad-ass-12a36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQWlFFq4vM4wPVSe1L0CJaBeaTrKN3NfE',
    appId: '1:868184915846:ios:9b9291f207c3f925873607',
    messagingSenderId: '868184915846',
    projectId: 'mad-ass-12a36',
    databaseURL: 'https://mad-ass-12a36-default-rtdb.firebaseio.com',
    storageBucket: 'mad-ass-12a36.appspot.com',
    iosBundleId: 'com.katepo.demo.madDemo',
  );
}
